CREATE TABLE customer (
    customer_id INTEGER PRIMARY KEY,
    age INTEGER,
    gender VARCHAR(20),
    item_purchased VARCHAR(100),
    category VARCHAR(50),
    purchase_amount_usd INTEGER,
    location VARCHAR(100),
    size VARCHAR(10),
    color VARCHAR(50),
    season VARCHAR(20),
    review_rating DECIMAL(3,1),
    subscription_status VARCHAR(20),
    shipping_type VARCHAR(50),
    discount_applied VARCHAR(20),
    previous_purchases INTEGER,
    payment_method VARCHAR(50),
    frequency_of_purchases VARCHAR(30),
    age_group VARCHAR(30),
    purchase_frequency_days DECIMAL(10,1)
);

SELECT COUNT(*) FROM customer;
SELECT * FROM customer;

--Q1. What is the total revenue generated by male vs female customers?
create view Total_revenueByGender AS
select gender,sum(purchase_amount_usd) 
as revenue 
from customer 
group by gender;

select * from Total_revenueByGender;

--Q2. Which customer used a discount but still spent more than the average purchase amount?
create view Customer_paying_more_than_average_after_discount AS
select customer_id , purchase_amount_usd ,(Select Avg(purchase_amount_usd) from customer) as avg_spent
from customer
where discount_applied = 'Yes' 
and purchase_amount_usd > (Select Avg(purchase_amount_usd) from customer);

select * from Customer_paying_more_than_average_after_discount;

--Q3. Which are the top 5 products with the highest average review rating?
select item_purchased, Round(avg(review_rating),2) from customer 
group by item_purchased
order by avg(review_rating) desc limit 5;

order by avg(review_rating) desc limit 5;order by avg(review_rating) desc limit 5;
--Q4. Compare the average Purchase Amounts between Standard And Express Shipping.
select shipping_type, 
Round(avg(purchase_amount_usd),2)
from customer 
where shipping_type in ('Standard','Express')
group by shipping_type;

--Q5. Do subscribed customers spend more?
--Compare average Spend and total revenue between subscribers and non-subscribers.
select subscription_status, 
count(customer_id) as total_customers,
Round(Avg(purchase_amount_usd),2) as Average_spend, 
Round(sum(purchase_amount_usd),2) as Total_revenue
from customer
group by subscription_status 

--Q6. Which 5 products have the highest % of purchases with discounts applied ?
select item_purchased,
Round(Sum(CASE when discount_applied = 'Yes' THEN 1 else 0 END)*100.0 /Count(*),2) as Discount_rate
from customer
group by item_purchased
order by discount_rate desc limit 5;

--Q7. Segment customers into New, Returning, And Loyal based on their total
--number of previous purchases, and show the count of each segment.
Select 
CASE 
WHEN previous_purchases<=1 Then 'New' 
WHEN previous_purchases between 2 and 5 THEN 'Returning'
else 'Loyal' END as Customer_behavior,
count(*) as Customer_count 
from customer
group by Customer_behavior
order by customer_count DESC;

--Q8. What are top 3 most purchased products within each category?
WITH product_counts AS (
    SELECT
        category,
        item_purchased,
        COUNT(*) AS purchase_count
    FROM customer
    GROUP BY category, item_purchased
),
ranked_products AS (
    SELECT
        category,
        item_purchased,
        purchase_count,
        ROW_NUMBER() OVER (
            PARTITION BY category
            ORDER BY purchase_count DESC
        ) AS product_rank
    FROM product_counts
)
SELECT
    category,
    item_purchased,
    purchase_count
FROM ranked_products
WHERE product_rank <= 3
ORDER BY category, product_rank;

-----
WITH item_counts AS (
    SELECT
        category,
        item_purchased,
        COUNT(customer_id) AS total_orders,
        ROW_NUMBER() OVER (
            PARTITION BY category
            ORDER BY COUNT(customer_id) DESC
        ) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)
SELECT
    item_rank,
    category,
    item_purchased,
    total_orders
FROM item_counts
WHERE item_rank <= 3
ORDER BY category, item_rank;

--Q9. Are customers who are repeat buyers(more than 5 previous purchases) also likely to buy subscription?
select subscription_status, 
count(customer_id) as repeat_buyers
from customer
where previous_purchases>5
group by subscription_status;

--Q10. What is the revenue contribution of each age group ?
select age_group, sum(purchase_amount_usd) as total_revenue
from customer
group by age_group
order by total_revenue desc;